# Generated by Django 4.0.6 on 2022-08-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
    ]
