# Generated by Django 4.0.6 on 2022-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_task_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
