# Generated by Django 4.0.6 on 2022-08-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_label_attachlabeltotask_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachlabeltotask',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task_manager.task'),
        ),
        migrations.AlterField(
            model_name='attachlabeltotask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_manager.label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='task_manager.AttachLabelToTask', to='task_manager.label'),
        ),
    ]
