# Generated by Django 4.0.6 on 2022-08-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_attachlabeltotask_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachlabeltotask',
            old_name='label',
            new_name='attach_label',
        ),
        migrations.RenameField(
            model_name='attachlabeltotask',
            old_name='task',
            new_name='attach_task',
        ),
    ]
