# Generated by Django 4.0.6 on 2022-08-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_rename_labels_task_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='label',
            new_name='labels',
        ),
    ]
